<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Company>tom-englert.de</Company>
    <Product>Tom's Toolbox</Product>
    <Copyright>Copyright (c) tom-englert.de and Contributors.</Copyright>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IsDeploymentTarget>true</IsDeploymentTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.1" PrivateAssets="all" />
    <PackageReference Include="Throttle.Fody" Version="1.7.0" PrivateAssets="all" />
    <PackageReference Include="TomsToolbox.Wpf.Styles" Version="2.21.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
